# Generated by Django 3.2.9 on 2021-11-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('draft', 'Borrador')], default='active', max_length=10),
        ),
    ]
